name: Auto Release with Versioning

on:
  push:
    branches:
      - main  # Change if you want another branch

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: |
          latest=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest=$latest" >> $GITHUB_ENV
          echo "Latest tag: $latest"

      - name: Bump patch version
        id: bump_version
        run: |
          IFS='.' read -r major minor patch <<< "${{ env.latest//v/ }}"
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "New tag: $new_tag"

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_tag }}
          name: "Release ${{ env.new_tag }}"
          body: "Automated release for commit ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload files as assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_tag }}
          files: |
            **/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
